version: '3.4'

services:
  newsy.web:
    image: ${DOCKER_REGISTRY-}api
    container_name: newsy_web
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    volumes:
      - ./src/IdentityServer:/root/IdentityServer:cached
      - ${USERPROFILE}/.aspnet/https:/https/
    environment:
      - ASPNETCORE_URLS="https://+;"
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=a
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - newsy.db

  newsy.db:
    image: postgres:13.2
    container_name: newsy_db
    environment:
      - POSTGRES_DB=newsy_data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: identityserver/Dockerfile
    ports:
      - 44342:80
      - 44343:443
    volumes:
      - ./src/Api:/root/Api:cached
      - ${USERPROFILE}/.aspnet/https:/https/
    environment:
      - ASPNETCORE_URLS="https://+;"
      - ASPNETCORE_HTTPS_PORT=44343
      - ASPNETCORE_Kestrel__Certificates__Default__Password=a
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx